# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-08 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_user_pteam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pteam',
            new_name='pteams',
        ),
    ]
